name: CI Pipeline for Model Update

on:
  push:
    paths:
      - churn-model*.pkl  # Détecte les changements dans les fichiers de modèle
      - data/**            # Détecte les changements dans les données
    branches:
      - main  # Surveille la branche `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t churn-app .

    - name: Deploy to Heroku
      run: |
        heroku container:login
        heroku container:push web --app <your-heroku-app-name>
        heroku container:release web --app <your-heroku-app-name>
