name: CI for Churn Prediction

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape pour entraîner et sauvegarder le modèle
    - name: Train model
      run: |
        python train.py  # Assurez-vous que ce script crée churn-model.pkl

    # Étape pour exécuter les tests
    #- name: Run tests
     # run: |
     #   pytest test_app.py

    # Étape pour installer Heroku CLI
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        
    # Configurer Git pour utiliser Heroku API
    - name: Set up Heroku remote
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    # Pousser vers Heroku
    - name: Deploy to Heroku
      run: |
        git push heroku master:mai
