name: Deploy to Heroku

on:
  push:
    branches:
      - master  # Ce pipeline s'exécutera à chaque push sur la branche `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: HRKU-77b4629c-066e-4637-b716-c1682328194f
      run: |
        heroku container:login
        heroku container:push web --app churn-app
        heroku container:release web --app churn-app
